### ISSUE TITLE
Improvement of the scoring system

### ISSUE THREAD

**Issue by necropotame** [necropotame/teeworlds-infclass#11]
+5 per survivor
+1 to the portal owner if a zombie dies just after teleportation

**Comment by TheRealOrangus** [comment]
> +1 to the portal owner if a zombie dies just after teleportation.

Or better like this, the score counts when the zombie dies, if all of the following conditions are true:
* Time after the zombie came out from the portal isn't out.
* The zombie touched ground or hooked(hookable tile, or other tee)
* The zombie was not hooked by other player(human or zombie, does not matter)

So it then would work for traps with spikes(death tiles) as well.

Time limit after the zombie came out from the portal, should be like 5 seconds or **more**, because there are other conditions, and with good imagination of this process in our minds, giving nice results.

If you are not sure about these, check them out in real tests first, and only then judge.
