### ISSUE TITLE
No lonely ghouls

### ISSUE THREAD

**Issue by duralakun** [necropotame/teeworlds-infclass#123]
Suggestion: Dont create Ghouls before there are atleast 6 infected.
Reason: Ghouls are not so good if they dont have infected dieing next to them. Being the startzombie as ghoul is boring

**Comment by necropotame** [comment]
I agree

**Comment by Socialdarwinist** [comment]
Letting ghouls spawn only after 6 infected is too much. In fact, a ghoul is already useful with 2 zombies if one dies intentionally (which is also encouraged by inf_barrier_timereduce) – it is just not likely, because too often the other zombie is too dopey to do that. So, not letting ghouls spawn as starter but elsewhen is agreeable.

**Comment by Socialdarwinist** [comment]
This issue has been fixed on Feb 15, 2017, with the commits baa1b8d6f8f26fc2e3ed68ec722a6154370a816f and 5abc667f3954427826bec95a6d25eb38575edadb.
