### ISSUE TITLE
Mercenary Grenade change

### ISSUE THREAD

**Issue by duralakun** [necropotame/teeworlds-infclass#165]
How about changing the grenades so that they explode as soon as an infected is in range, and give them a time limit. 3 seconds after the grenade is shot it will explode even if no infected is in range.
Also remove the ability to trigger the explosion of the grenades. Launcher can only shot them and doesnt switch mode. (this would allow to shoot more grenades in a short time, therefore maybe the shooting speed need to be nerfed a bit)

Positive Effects:
- less entities lying around
- easier for new people

**Comment by Socialdarwinist** [comment]
“Infected in range” – might be too early. I often try to let the grenades explode in a way multiple zombie will be affected. Also it is nice to shoot multiple times into (multiple) hordes of zombies to hit more. The current system is excellently balanced.

But what you propose, has multiple complications that are difficult to convey to players, is hard to balance because of questionable time, frequency, damage and range parameters, and possibly prone to plain bugs because of its entanglements. On top of all, even if your idea is rationally implemented, it still cannot be accepted because what has subsisted now for long as mercenary weapon is what constitutes a cherished stock of Infection Class gameplay.

The only frame in which the poison grenades might be altered is inside of a new class. But then again and even more because of needed other means of defense except this new weapon, you have to balance, and to propose a more profound draft.
If it ain’t broke, don’t fix it.
