### ISSUE TITLE
vote disabled

### ISSUE THREAD

**Issue by argon-radio** [necropotame/teeworlds-infclass#48]
is there a possibility to ad voting on players again? only to move them to the spetators, cause sometimes there are annoying trolls who abuse the fact that they cant get banned by vote.

**Comment by TheRealOrangus** [comment]
Bad idea, it would be even worse, I know this by my own experince when I was moving _"The trolls"_ to spectators on server where votekick is disabled, they start spam so much that everyone leaves.

**Comment by argon-radio** [comment]
at ifcity they have spamprotection, like if a player sends too many messages in a specific time, he gets muted for 1 minute.

**Comment by gwilherm** [comment]
Orangus: maybe then people will find out that even vanilla client has mute feature :D

**Comment by gwilherm** [comment]
But i agree that server-side spam protection is good thing :) even if i sometimes get muted when I abuse of bound messages "xD"

**Comment by necropotame** [comment]
I will not enable the vote system again because the number of abuse with it is far more important than without. For the spam protection, I will do it when I will port InfectionClass to ModAPI.

**Comment by liwakura** [comment]
Having Votekick disabled takes any possibility to deal with trolls. Things players can do NOTHING about:

- Witches near spikes
- Zombies blocking entrances to human hideouts
- Teamhooking and Sabotaging
- Teamkills by pushing and pulling into spikes (or engineer walls)

This makes the gameplay incredibly frustrating, and people will just leave en masse.
This has gotten even worse since people know they will face no consequences.

**Comment by necropotame** [comment]
Troll-witch will be solved by defining area where infected can't spawn.
