### ISSUE TITLE
A better version of the ghost

### ISSUE THREAD

**Issue by IncredibleCake** [necropotame/teeworlds-infclass#56]
Hello !

I often play InfClass and I noticed the ghost has nearly no special abilities : the radius of invisibility is too large. It's like if he was visible only when he is in the sight line of human, which doesn't make a lot of sense. I think reducing this radius may make him more powerful, but I also think that there's more interesting features we can add to him to make him more useful : 

- When it doesn't move, the radius is shorter (or, more generally, the faster he goes, the wider the radius)
- Radius gets extra smaller when ghost is looking down (like if he closes his eyes)

This would allow a ghost to efficiently hide like, I suppose, he was designed for. 
I think I could help coding this, but I don't have much time and I first want your opinion.
Thanks for reading

**Comment by necropotame** [comment]
The Ghost is hard to balance. The radius must of the correct length so that it's possible but hard for humans to avoid him. In my opinion, the actual size is enough or may be a little too big in open area, but clearly too big in corridors. A good solution is to take into account the visibility. Like, instead of using a radius, using a path length from the ghost tile to the nearest human tile. The algorithm is more or less implemented for the flash grenade of the ninja.

**Comment by IncredibleCake** [comment]
Well I also thought of using path length but (I don't whether it's such a problem or not), pathfinding algorithm are pretty slow. I took a quick look at the flash grenade code, I don't know if it works. Still, using path length instead of direct length should help.
