### ISSUE TITLE
Update infclass to bam 5.0

### ISSUE THREAD

**Issue by ObaniGemini** [necropotame/teeworlds-infclass#70]
InfClass mod is not compatible with the new ![BAM release](https://github.com/matricks/bam/releases)

Teeworlds organization adapted the program to this release in ![that commit](https://github.com/teeworlds/teeworlds/commit/d6f3cc159257a2d6033e3ef46906c72c9db1b9eb)

**Comment by necropotame** [comment]
This commit is for TeeWorlds 0.7, not TeeWorlds 0.6. So InfClass should stay with bam 4.0. However, InfClass will be never ported on TeeWorlds 0.7 because of the newly introduced limitation of the game: no clan and skin change during the game, no broadcast, ...
So InfClass will be ported instead on TeeUniverses, that is based on 0.7, but with more feature and cross compatibility with 0.6. bam 5.0 will be used.
