### ISSUE TITLE
Computation of top10 seems to take the best rounds of a user

### ISSUE THREAD

**Issue by ProgVal** [necropotame/teeworlds-infclass#74]
Hi,

From what I understand from [the big SQL query](https://github.com/necropotame/teeworlds-infclass/blob/779c61dfbdef9e7a7b4eafb5e3cc848827d51641/src/engine/server/server.cpp#L2878-L2908), the top10 is computed like this:
* all scores are fetched (innermost `SELECT`), and ordered by user then by round score of that user (`ORDER BY TableRoundScore.UserId ASC, TableRoundScore.Score DESC`)
* for each one of the rows of score of a user, a RowNumber is computed (`@VarRowNum := IF(@VarType = x.UserId, @VarRowNum + 1, 1) as RowNumber`) such that if `RowNumber` is 42 (for instance) it means that row corresponds to the 42nd best round for that player
* rows with high `RowNumber` are discarded (`WHERE y.RowNumber <= %d`)

My understanding is that the top10 score is computed by summing the top `SQL_SCORE_NUMROUND` rounds of a user.

Is this on purpose?
Generally, I would expect a top10 to be based on the average score of a user.

**Comment by necropotame** [comment]
It's on purpose. Commonly, two ways are used to compute a score: a sum or an average. Using a sum lead to encourage people to play often, but not necessary well. Using an average lead to incoherent result if you play well but you chat often and you are afk some times. The "sum of 32 best score" is a compromise. Since it's based on the best score, you not decrease your rank when you are playing not seriously. And because I use the 32 best score, people need a lot of effort to increase it, even if they cheat (like if you win with 200 points, but you don't play well often, this score will not increase that much your rank).

**Comment by ProgVal** [comment]
I see. Thanks.
